// Generated by CoffeeScript 1.12.2
(function() {
  var exp_days, lat, limit, lng, msr, radius, timeout, unit;

  lat = 37.4204;

  lng = -122.1031;

  timeout = 5000;

  radius = 5;

  limit = 20;

  msr = 1;

  exp_days = 365;

  if (!getCookie('unit')) {
    setCookie('unit', unit, exp_days);
  } else {
    unit = getCookie('unit');
  }

  if (!getCookie('radius')) {
    setCookie('radius', radius, exp_days);
  } else {
    radius = getCookie('radius');
  }

  if (!getCookie('msr')) {
    setCookie('msr', msr, exp_days);
  } else {
    msr = getCookie('msr');
  }

  $(function() {
    var callback, source, template;
    source = $("#entry-template").html();
    template = Handlebars.compile(source);
    if ("geolocation" in navigator) {
      navigator.geolocation.getCurrentPosition(function(position) {
        lat = position.coords.latitude;
        lng = position.coords.longitude;
      });
    }
    callback = function() {
      var url;
      console.log("Lng:" + lng + " Lat:" + lat);
      url = "get/" + lat + "/" + lng + "/" + radius + "/" + limit + "/" + msr;
      return $.getJSON(url, function(data) {
        var context, html;
        console.log(data);
        context = {
          shops: data
        };
        html = template(context);
        return $('#shops-table').html(html);
      });
    };
    $('#shops-table').on('click', 'table tbody tr', function() {
      var poi_id, url;
      poi_id = ($(this).attr('id')).replace('_', '');
      url = "poi/" + poi_id + "/" + lat + "/" + lng + "/" + msr;
      return window.location.href = url;
    });
    return setTimeout(callback, timeout);
  });


  /*
  Lng:-0.3908627 Lat:51.6722505
  Lng:-0.3908627 Lat:51.6722505
  Lng:-0.3908627 Lat:51.6722505
  Lng:-0.3887132 Lat:51.6641152
  Lng:-0.3887169 Lat:51.664111399999996
   */

}).call(this);
